---
title: "bjl21500-s_place"
author: "Briana Lettsome"
date: "October 31, 2018"
output: html_document
---

```{r}
library(viridis)
library(plotly)
library(tidyverse)
library(httr)
library(jsonlite)
```


```{r}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() %>%
  sample_n(1000)


# Wrangled and tidied the imported data to create a new dataset 
nyc_restaurants = nyc_inspections %>%
  janitor::clean_names() %>%
  select(boro, cuisine_description, grade, street, score) %>%
  filter(boro != "Missing") 
```



# Graph 1
```{r}
# Using the selelct, filter and count function in order to extract top-ranked eats
twonyc_grades = nyc_restaurants %>%
  select(grade, boro) %>%
  filter(grade %in% c("A", "B"), boro != "Missing") %>%
  count(boro)
  
# Making of bar graph to show the distribution of grade A and B restaurants per boro
plot_ly(twonyc_grades, x = ~boro, y = ~n, color = ~boro, type = "bar")
```


# Graph 2
```{r}
nyc_scores = nyc_restaurants %>%
    select(score, grade, boro) %>%
    filter(grade %in% c("A", "B", "C",
                      score %in% 0:50)) 


## Scatterplot 
plot_ly(nyc_scores, x = ~grade, y = ~score, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~boro)
```

#Graph 3
```{r}
nyc_cuisine = nyc_restaurants %>%
  select(grade, score, boro, cuisine_description) %>%
  filter(cuisine_description == "Chinese",
        grade %in% c("A", "B"), boro != "Missing")
  

nyc_cuisine %>%
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2")
```

